### ISSUE TITLE
brew install too many errors

### ISSUE THREAD

**Issue by emfrid** [adamritter/homebrew-fastgron#1]
Unable to install via Homebrew
`Last 15 lines from .../Library/Logs/Homebrew/fastgron/02.cmake:
In file included from /tmp/fastgron-20230531-12390-31i8cd/fastgron-0.4.6/extern/fast_io/fast_io_core.h:85:
In file included from /tmp/fastgron-20230531-12390-31i8cd/fastgron-0.4.6/extern/fast_io/fast_io_core_impl/integers/integer.h:7:
/tmp/fastgron-20230531-12390-31i8cd/fastgron-0.4.6/extern/fast_io/fast_io_core_impl/integers/impl.h:385:109: error: no template named 'bit_cast' in namespace 'std'; did you mean simply 'bit_cast'?
                        return ::fast_io::manipulators::scalar_manip_t<cache,uintptr_alias_type>{static_cast<uintptr_alias_type>(::std::bit_cast<std::uintptr_t>(t))};
                                                                                                                                 ^~~~~~~~~~~~~~~
                                                                                                                                 bit_cast
/tmp/fastgron-20230531-12390-31i8cd/fastgron-0.4.6/extern/fast_io/fast_io_core_impl/utils.h:17:5: note: 'bit_cast' declared here
 To bit_cast(From const& src) noexcept
    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [CMakeFiles/fastgron.dir/src/fastgron.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/fastgron.dir/all] Error 2
make: *** [all] Error 2`

**Comment by adamritter** [comment]
Can you try the new version? 0.4.8

I got rid of that dependency.

Also I just added it to homebrew official library :)

Brew install fastgron should work

**Comment by emfrid** [comment]
Cleaned up the brew cache and `brew install fastgron` worked nicely. FYI, version referenced in download is still 0.4.7

Thanks! Looking forward to this saving me some time and headache!

**Comment by adamritter** [comment]
Thanks, please write some feedback, there are lots of downloads, but no
feedback after people using it.
